name: Build and Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build and Test
        run: dotnet build --configuration Release

      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        with:
          asset_name: 'windows-binary'
          asset_path: './bin/Release/net5.0/win-x64/publish'
          asset_content_type: application/zip

      - name: Upload Mac Binary
        uses: actions/upload-release-asset@v1
        with:
          asset_name: 'mac-binary'
          asset_path: './bin/Release/net5.0/osx-x64/publish'
          asset_content_type: application/zip

      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        with:
          asset_name: 'linux-binary'
          asset_path: './bin/Release/net5.0/linux-x64/publish'
          asset_content_type: application/zip
