name: Build for Linux

on:
  push:
    tags:
      - "*"

# on:
#   push:
#     branches:
#       - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build the Project
        run: dotnet build --no-restore
      - name: Test the Code
        run: dotnet test --no-build --verbosity normal
      - name: Build for Linux
        run: dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained true -p:PublishReadyToRun=false
      - name: Rename for Publishing
        run: mv "bin/Debug/net5.0/linux-x64/publish/sledge" "bin/Debug/net5.0/linux-x64/publish/sledge-linux"
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "bin/Debug/net5.0/linux-x64/publish/sledge-linux"
          token: ${{ secrets.GITHUB_TOKEN }}
