name: Build for MacOS

on:
  push:
    tags:
      - "*"

# on:
#   push:
#     branches:
#       - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build the Project
        run: dotnet build --no-restore
      - name: Test the Code
        run: dotnet test --no-build --verbosity normal
      - name: Build for MacOS
        run: dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained true -p:PublishReadyToRun=false
      - name: Bundle for MacOS
        run: mkdir Sledge.app; mkdir Sledge.app/Contents; mkdir Sledge.app/Contents/MacOS; mkdir Sledge.app/Contents/Resources; mv "bin/Debug/net5.0/osx-x64/publish/*" "Sledge.app/Contents/MacOS"; cp ".github/build/Info.plist" "Sledge.app/Contents/Info.plist"; cp ".github/build/Icon.icns" "Sledge.app/Contents/Icon.icns"; zip -r "Sledge-OSX.zip" "Sledge.app"
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "Sledge-OSX.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
